### PR TITLE
Add app_env var for script timeout

### PR DESCRIPTION
**Pull request by russelldb**
js_driver:eval_js/2 uses a macro SCRIPT_TIMEOUT for the amount of
time to wait for a js script to execute before timing out. In some
instances (testing JS map reduce on limited hardware) it would be
handy to set this timeout higher.

Use the 'erlang_js' app_env var 'script_timeout' and any int value.
Timeout is in milliseconds.

### CODE REVIEW

**Comment by joedevivo** [comment]
+1 this worked great in riak 1.2.1 with `riak_test`, but I did have to rebase before rebar would allow the dependency to work.

**Comment by strange** [comment]
Our use application:get_env/2? A little messier, but nice to get rid of the dep.

**Comment by cmeiklejohn** [comment]
`app_helper` is only going to work when bundled with riak/riak_core.  Should this be modified to use `application:get_env` as recommended above?

**Comment by cmeiklejohn** [comment]
Closing in favor of #41.

**Pull request closed without merging**
