### PR TITLE
Resolve build problems on Mountain Lion.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
Use the riak bundled rebar, as the currently bundled version doesn't use
honor port_env options.

Correctly detect Mountain Lion, and no longer apply the -m32 and -arch
i386 build options due to false detection of other Mac OS X version.

### CODE REVIEW

**Comment by seancribbs** [comment]
:+1: wfm, but I suppose @elight should try it as well since he reported the problem. (I'm on OS X 10.8.4 fwiw)

**Comment by jaredmorrow** [comment]
@seancribbs did you try with a erlang built specifically as 32bit?

**Comment by elight** [comment]
Planning on it tomorrow

**Comment by seancribbs** [comment]
@jaredmorrow Negatory, about to.

**Comment by seancribbs** [comment]
So, I built a 32-bit R16B01 and JS still seems to be built with the -m64 flag because of the detected architecture, the Erlang build arch is ignored. I don't know whose problem this is, but I might also add that against R16, these warnings were generated:

```
c_src/spidermonkey_drv.c:82:3: warning: 'driver_output_term' is deprecated [-Wdeprecated-declarations]
  driver_output_term(dd->port, terms, sizeof(terms) / sizeof(terms[0]));
  ^
/Users/sean/erlang/R16B01-32/lib/erlang/erts-5.10.2/include/erl_driver.h:617:12: note: 'driver_output_term' declared here
EXTERN int driver_output_term(ErlDrvPort ix,
           ^
c_src/spidermonkey_drv.c:256:3: warning: 'driver_output_term' is deprecated [-Wdeprecated-declarations]
  driver_output_term(dd->port,
  ^
/Users/sean/erlang/R16B01-32/lib/erlang/erts-5.10.2/include/erl_driver.h:617:12: note: 'driver_output_term' declared here
EXTERN int driver_output_term(ErlDrvPort ix,
           ^
```

**Comment by cmeiklejohn** [comment]
It was my impression that a 32-bit Erlang on Mountain Lion has to be built -m64 because Mountain Lion is the first all 64-bit release of OS X, and the machine architecture.  Is this not correct?  

I also believe that those warnings also occur if you omit the -m64 flag and built without it.

**Comment by seancribbs** [comment]
@cmeiklejohn Right, those warnings are irrelevant to the architecture... I'm going to retry on an R15.

**Comment by jaredmorrow** [comment]
64bit erlang has always worked on OSX when built from the toplevel, that was never the issue.  The issue was when people used 32bit erlang, which we no longer support.

**Comment by cmeiklejohn** [comment]
Yes, I've confirmed this builds correctly with R15B03 32-bit Erlang, with the -m64 and -arch x86_64.

**Comment by jaredmorrow** [comment]
+1

**Comment by elight** [comment]
I still see this error when building with R15B03 32 bit and clang:

</img>

**Comment by cmeiklejohn** [comment]
Hrm, I'm not getting that error at all with R15B03 32-bit and clang; also it's concerning the first cc line has -m32, because the code this patch added was to remove that argument.  Did you make sure you did 'make distclean' before building?

**Comment by elight** [comment]
I did a "make clean" instead. But I had gone into the erlang_js dep and did a git pull. Same difference?

Anyway, building against with make distclean.

**Comment by jaredmorrow** [comment]
I just built a fresh erlang 15b01 32bit and my build also failed.
- erlang_js rev:  erlang_js REV master (via list-deps), sha is 89fdf951de2c (the tip of master)
- Erlang is R15B01-32

```
$ erl                                                                   
Erlang R15B01 (erts-5.9.1) [source] [smp:8:8] [async-threads:0] [hipe] [kernel-poll:false]
```
- Build output is https://gist.github.com/jaredmorrow/695417cb02ce815213eb

**Comment by cmeiklejohn** [comment]
OK, this definitely works on R16B01 32-bit.  I'll test R15B03 next.

**Comment by cmeiklejohn** [comment]
OK; now I think I've found the difference.

R16B01 32-bit build:

```
1> erlang:system_info(system_architecture).
"x86_64-apple-darwin12.4.0"
```

R15B03 32-bit build:

```
1> erlang:system_info(system_architecture).
"i386-apple-darwin12.4.0"
```

**Comment by cmeiklejohn** [comment]
@jaredmorrow Do you mind trying to build with the change in #40?  This produces a successful build for me under R15B03 32-bit.

**Comment by cmeiklejohn** [comment]
Resolved in basho/erlang_js#39.

**Pull request merged**
