### PR TITLE
Update erlang_js to use tools.mk

### PR DESCRIPTION
**Pull request by seancribbs**
- Add recent tools.mk
- Remove unneeded targets in GNUmakefile
- Remove rebar.mk
- Fix dialyzer warning in js_benchmark
- Fix xref queries/checks

### CODE REVIEW

**Comment by seancribbs** [comment]
This should clean up the build, making it all green.

**Comment by cmeiklejohn** [comment]
:+1: 997bb78

**Comment by seancribbs** [comment]
Bors is enabled here now, @cmeiklejohn. :smile:

**Comment by seancribbs** [comment]
@borshop merge

**Pull request merged**
